from token import Token

lookup = {
    '+': Token.ADDITION,
    ":=": Token.ASSIGNMENT,
    "begin": Token.BEGIN,
    "boolean": Token.BOOLEAN_TYPE,
    "boolean_type": Token.BOOLEAN_TYPE,
    ":": Token.COLON,
    "do": Token.DO,
    "else": Token.ELSE,
    "end": Token.END,
    "=": Token.EQUAL,
    "false": Token.FALSE,
    ">": Token.GREATER,
    ">=": Token.GREATER_EQUAL,
    "if": Token.IF,
    "integer": Token.INTEGER_TYPE,
    "integer_type": Token.INTEGER_TYPE,
    "<": Token.LESS,
    "<=": Token.LESS_EQUAL,
    "*": Token.MULTIPLICATION,
    '.': Token.PERIOD,
    "program": Token.PROGRAM,
    "read": Token.READ,
    ';': Token.SEMICOLON,
    '-': Token.SUBTRACTION,
    "then": Token.THEN,
    "true": Token.TRUE,
    "var": Token.VAR,
    "while": Token.WHILE,
    "write": Token.WRITE,
    "id": Token.IDENTIFIER,
    "$": Token.EOF,
    "integer_lit": Token.INTEGER_LITERAL,
}
